--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.2.78.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 04/09/2018 08.07.12
-- Server version: 5.5.5-10.1.10-MariaDB
-- Client version: 4.1
--


--
-- Definition for database db_gegana_app
--
DROP DATABASE IF EXISTS db_gegana_app;
CREATE DATABASE db_gegana_app
	CHARACTER SET utf8
	COLLATE utf8_general_ci;

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

-- 
-- Set default database
--
USE db_gegana_app;

--
-- Definition for table ms_bahan
--
CREATE TABLE ms_bahan (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  kode CHAR(9) NOT NULL,
  nama VARCHAR(255) NOT NULL,
  jumlah INT(11) UNSIGNED NOT NULL DEFAULT 0,
  harga DECIMAL(14, 2) NOT NULL,
  data_status VARCHAR(255) NOT NULL DEFAULT 'A',
  PRIMARY KEY (id),
  UNIQUE INDEX kode (kode)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table ms_customer
--
CREATE TABLE ms_customer (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  kode CHAR(15) NOT NULL,
  nama VARCHAR(255) NOT NULL,
  alamat VARCHAR(255) NOT NULL,
  no_telp VARCHAR(15) NOT NULL,
  data_status VARCHAR(255) NOT NULL DEFAULT 'A',
  PRIMARY KEY (id),
  UNIQUE INDEX kode (kode)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table ms_supplier
--
CREATE TABLE ms_supplier (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  kode CHAR(15) NOT NULL,
  nama VARCHAR(255) NOT NULL,
  alamat VARCHAR(255) NOT NULL,
  no_telp VARCHAR(15) NOT NULL,
  data_status VARCHAR(255) NOT NULL DEFAULT 'A',
  PRIMARY KEY (id),
  UNIQUE INDEX kode (kode)
)
ENGINE = INNODB
AUTO_INCREMENT = 3
AVG_ROW_LENGTH = 8192
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table tr_pembelian
--
CREATE TABLE tr_pembelian (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  kode_transaksi CHAR(15) NOT NULL,
  kode_supplier CHAR(15) NOT NULL,
  total_harga DECIMAL(14, 2) NOT NULL,
  data_status CHAR(1) NOT NULL DEFAULT 'A',
  tanggal TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE INDEX kode_transaksi (kode_transaksi)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table tr_pembelian_detail
--
CREATE TABLE tr_pembelian_detail (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  kode_transaksi CHAR(15) NOT NULL,
  kode_bahan CHAR(15) NOT NULL,
  jumlah INT(5) NOT NULL,
  total DECIMAL(14, 2) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table tr_penjualan
--
CREATE TABLE tr_penjualan (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  kode_transaksi CHAR(15) NOT NULL,
  kode_customer CHAR(15) NOT NULL,
  total_harga DECIMAL(14, 2) NOT NULL,
  data_status CHAR(1) NOT NULL DEFAULT 'A',
  tanggal TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE INDEX kode_transaksi (kode_transaksi)
)
ENGINE = INNODB
AUTO_INCREMENT = 9
AVG_ROW_LENGTH = 2340
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table tr_penjualan_detail
--
CREATE TABLE tr_penjualan_detail (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  kode_transaksi CHAR(15) NOT NULL,
  kode_bahan CHAR(15) NOT NULL,
  jumlah INT(5) NOT NULL,
  total DECIMAL(14, 2) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 15
AVG_ROW_LENGTH = 1170
CHARACTER SET utf8
COLLATE utf8_general_ci;

-- 
-- Dumping data for table ms_bahan
--
INSERT INTO ms_bahan VALUES
(1, 'BHN-00001', 'Katun A', 51, 35000.00, 'A');

-- 
-- Dumping data for table ms_customer
--
INSERT INTO ms_customer VALUES
(1, 'CUST-00001', 'Budi Karya', 'Jln. Turunan', '021-7498353', 'A');

-- 
-- Dumping data for table ms_supplier
--
INSERT INTO ms_supplier VALUES
(1, 'SPL-00001', 'PT. ABC DEF', '021-19283723', '021 3430984', 'A'),
(2, 'SPL-00002', 'PT. ANGIN RIBUT', 'Jln. Tanjakan', '021 3430984', 'A');

-- 
-- Dumping data for table tr_pembelian
--
INSERT INTO tr_pembelian VALUES
(1, 'TR-00001', 'SPL-00002', 350000.00, 'A', '2018-09-04 07:43:30');

-- 
-- Dumping data for table tr_pembelian_detail
--
INSERT INTO tr_pembelian_detail VALUES
(1, 'TR-00001', 'BHN-00001', 10, 350000.00);

-- 
-- Dumping data for table tr_penjualan
--
INSERT INTO tr_penjualan VALUES
(2, '123456', 'CUST-00001', 0.00, 'A', '2018-08-27 18:11:02'),
(3, 'TR-00002', 'CUST-00001', 210000.00, 'A', '2018-08-27 18:25:17'),
(4, 'TR-00003', 'CUST-00001', 210000.00, 'A', '2018-08-27 18:49:51'),
(5, 'TR-00004', 'CUST-00001', 350000.00, 'A', '2018-08-27 18:50:47'),
(6, 'TR-00005', 'CUST-00001', 105000.00, 'A', '2018-08-27 19:40:42'),
(7, 'TR-00006', 'CUST-00001', 175000.00, 'A', '2018-09-04 07:24:02'),
(8, 'TR-00007', 'CUST-00001', 140000.00, 'A', '2018-09-04 07:30:23');

-- 
-- Dumping data for table tr_penjualan_detail
--
INSERT INTO tr_penjualan_detail VALUES
(1, '123456', 'BHN-00001', 4, 0.00),
(2, 'TR-00002', 'BHN-00001', 3, 105000.00),
(3, 'TR-00002', 'BHN-00001', 2, 70000.00),
(4, 'TR-00002', 'BHN-00001', 1, 35000.00),
(5, 'TR-00003', 'BHN-00001', 1, 35000.00),
(6, 'TR-00003', 'BHN-00001', 2, 70000.00),
(7, 'TR-00003', 'BHN-00001', 3, 105000.00),
(8, 'TR-00004', 'BHN-00001', 1, 35000.00),
(9, 'TR-00004', 'BHN-00001', 2, 70000.00),
(10, 'TR-00004', 'BHN-00001', 3, 105000.00),
(11, 'TR-00004', 'BHN-00001', 4, 140000.00),
(12, 'TR-00005', 'BHN-00001', 3, 105000.00),
(13, 'TR-00006', 'BHN-00001', 5, 175000.00),
(14, 'TR-00007', 'BHN-00001', 4, 140000.00);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;